python run_test.py --feature=basic_binarized --samples=200 --n 30 --device cuda --save True
python run_test.py --feature=basic_chemo --samples=200 --n 30 --device cuda --save True
python run_test.py --feature=basic_genetic --samples=200 --n 30 --device cuda --save True
python run_test.py --feature=cancer_type_only --samples=200 --n 30 --device cuda --save True
python run_test.py --feature=genes_cancer_type --samples=200 --n 30 --device cuda --save True
python run_test.py --feature=genes_only --samples=200 --n 30 --device cuda --save True
python run_test.py --feature=no_genes --samples=200 --n 30 --device cuda --save True
python run_test.py --feature=no_labs --samples=200 --n 30 --device cuda --save True
python run_test.py --feature=simple --samples=200 --n 30 --device cuda --save True
