python hyperparam.py --feature main 
python hyperparam.py --feature no_labs
python hyperparam.py --feature simple
python hyperparam.py --feature genes_only
python hyperparam.py --feature genes_cancer_type
python hyperparam.py --feature cancer_type_only
python hyperparam.py --feature basic_chemo
python hyperparam.py --feature basic_genetic
python hyperparam.py --feature basic_binarized
